services:
  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - SECRET_KEY=production_secret_key
      - JWT_SECRET_KEY=production_jwt_secret_key
      - DATABASE_URI=mysql+pymysql://root:root@117.72.200.129:6007/industrial_knowledge
      - PORT=${BACKEND_PORT:-5000}
      - MAX_CONTENT_LENGTH=209715200
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - app_network

  # 前端Web服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    depends_on:
      - backend      
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - BACKEND_URL=http://backend:${BACKEND_PORT:-5000}
      - VITE_APP_BASE_API=
    networks:
      - app_network

# 网络配置
networks:
  app_network:
    driver: bridge
