version: '3'

services:
  # 后端API服务 - 简化版
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - SECRET_KEY=test_secret_key
      - JWT_SECRET_KEY=test_jwt_secret_key
      - DATABASE_URI=sqlite:///industrial_knowledge.db
      - PORT=${BACKEND_PORT:-5000}
      # 添加超时相关设置
      - PIP_TIMEOUT=300
      - PIP_DEFAULT_TIMEOUT=300
      - PIP_RETRIES=10
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - app_network
    command: >
      sh -c "python run.py"

  # 前端Web服务 - 简化版
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - BACKEND_URL=http://backend:${BACKEND_PORT:-5000}
    networks:
      - app_network

# 持久化卷
volumes:
  uploads_data:

# 网络配置
networks:
  app_network:
    driver: bridge
